trigger:
- main

pool:
  name: Default
  #vmImage: ubuntu-latest

variables:
  projectRoot: '$(System.DefaultWorkingDirectory)/Azure_DevOps_Func'

stages:
- stage: Build
  jobs:
  - job: clean
    displayName: Clean agent build DIR
    workspace:
      clean: all
  
  - job: buildapp 
    displayName: Build and restore app
    steps:
    - script: |
        dotnet restore
        dotnet build --configuration Release
      workingDirectory: $(projectRoot)
  
  - job: publishapp
    dependsOn: buildapp
    displayName: Publish and zip application project file
    steps:
    # - task: DotNetCoreCLI@2
    #   inputs:
    #     command: 'publish'
    #     publishWebProjects: false
    #     projects: '*.csproj'
    #     arguments: '--configuration Release'
    #     zipAfterPublish: false
    #     modifyOutputPath: false
    #     workingDirectory: '$(System.DefaultWorkingDirectory)/Azure_DevOps_Func'
    
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/Azure_DevOps_Func'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
        verbose: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  dependsOn: Build
  jobs:
    - job: 
      displayName: Download build artifacts
      steps:
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)'
            cleanDestinationFolder: true
    
    - job: Deployapp
      displayName: Deploy function app
      steps:
      - task: AzureFunctionApp@2
        inputs:
          connectedServiceNameARM: 'Az_SVC_Connection'
          appType: 'functionAppLinux'
          appName: 'azure-devOps-func'
          package: '$($(System.ArtifactsDirectory)'
          runtimeStack: 'DOTNET-ISOLATED|7.0'
          deploymentMethod: 'runFromPackage'