trigger:
   - main

pool:
   name: Default

variables:
   app_name: azure-devops-func
   working_directory: '$(System.DefaultWorkingDirectory)/azure_func_devops'
   image_repo: 'openops/demo-function'

jobs:
   - job: clean
     displayName: Clean agent working dir
     workspace:
        clean: all

   - job: update
     dependsOn: clean
     displayName: Restore application
     steps:
      - script: |
          dotnet restore
          dotnet build --configuration Release
        displayName: Build and restore application
        workingDirectory: '$(working_directory)'
      
      - task: DotNetCoreCLI@2
        displayName: Dotnet publish
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: '*/*.csproj'
          arguments: '--configuration Release --output publish_output'
          zipAfterPublish: false
          modifyOutputPath: false
          workingDirectory: '$(working_directory)'
      
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(working_directory)/publish_output'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          replaceExistingArchive: true
          verbose: true
      
      - task: PublishBuildArtifacts@1
        displayName: Publish Build Artifacts
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          ArtifactName: 'drop'
          publishLocation: 'Container'

      - task: AzureFunctionApp@2
        displayName: Update function code
        inputs:
          connectedServiceNameARM: 'Az_SVC_Connection'
          appType: 'functionAppLinux'
          appName: 'azure-devops-func'
          package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          runtimeStack: 'DOTNET-ISOLATED|7.0'
          deploymentMethod: 'zipDeploy'