trigger:
   - main

pool:
   name: Default

variables:
   app_name: azure-devops-func
   working_directory: $(System.DefaultWorkingDirectory)/azure_func_devops

jobs:
   - job: clean
     displayName: Clean agent working dir
     workspace:
        clean: all

   - job: restore
     displayName: Restore application
     steps:
      - task: CmdLine@2
        inputs:
          script: |
            dotnet builld
            dotnet restore
          workingDirectory: '$(working_directory)'
   
      - task: AzureFunctionAppContainer@1
        displayName: Deploy container
        inputs:
          azureSubscription: 'Az_SVC_Connection'
          appName: '$(app_name)'
          imageName: 'openops/demo-function:0.0.1'

   