trigger:
   - main

pool:
   name: Default

variables:
   app_name: azure-devops-func
   working_directory: '$(System.DefaultWorkingDirectory)/azure_func_devops'
   image_repo: 'openops/demo-function'

jobs:
   - job: clean
     displayName: Clean agent working dir
     workspace:
        clean: all

   - job: update
     dependsOn: clean
     displayName: Restore application
     steps:
      - task: CmdLine@2
        inputs:
          script: |
            dotnet build
            dotnet restore
          workingDirectory: '$(working_directory)'

      - task: Docker@2
        displayName: docker login
        inputs:
          containerRegistry: 'Dockrer-Hub-Connection'
          command: 'login'

      - task: Docker@2
        displayName: docker build image
        inputs:
          containerRegistry: 'Dockrer-Hub-Connection'
          repository: '$(image_repo)'
          command: 'build'
          Dockerfile: '$(System.DefaultWorkingDirectory)/azure_func_devops/Dockerfile'

      - task: Docker@2
        displayName: docker push
        inputs:
          containerRegistry: 'Dockrer-Hub-Connection'
          repository: '$(image_repo)'
          command: 'push'
   
      - task: AzureFunctionAppContainer@1
        displayName: Deploy container
        inputs:
          azureSubscription: 'Az_SVC_Connection'
          appName: '$(app_name)'
          deployToSlotOrASE: true
          resourceGroupName: 'test-rg'
          slotName: 'production'
          imageName: $(image_repo):$(Build.BuildId)

   