---
volumes:
   prometheus-data:
      driver: local
   grafana-data:
      driver: local
   node_exporter_data:
      driver: local

services:
   node_exporter:
      privileged: true
      image: quay.io/prometheus/node-exporter:latest
      container_name: node_exporter
      ports:
         - 9100:9100
      command:
         - "--path.rootfs=/host"
      # network_mode: host
      pid: host
      restart: unless-stopped
      volumes:
         - "node_exporter_data:/host:ro,rslave"

   alertmanager:
      depends_on:
         - node_exporter
      image: prom/alertmanager:latest
      container_name: alertmanager
      privileged: true
      volumes:
         - ./alertmanager.yml:/etc/prometheus/alertmanager.yml
         - ./webhook.yml:/etc/prometheus/webhook.yml
      command:
         - "--config.file=/etc/prometheus/webhook.yml"
      ports:
         - "9093:9093"
      restart: unless-stopped

   prometheus:
      depends_on:
         - alertmanager
      image: docker.io/prom/prometheus:latest
      container_name: prometheus
      ports:
         - 9090:9090
      command: "--config.file=/etc/prometheus/prometheus.yaml"
      volumes:
         - ./prometheus.yml:/etc/prometheus/prometheus.yaml:ro
         - prometheus-data:/prometheus
         - ./alertingrules.yml:/etc/prometheus/alertingrules.yml
      restart: unless-stoppeddepends_on

   grafana:
      depends_on:
         - prometheus
      image: grafana/grafana:latest
      container_name: grafana
      ports:
         - 3000:3000
      volumes:
         - grafana-data:/var/lib/grafana
      restart: unless-stopped
